#!/usr/bin/env bash
set -eu
readonly NAME="$(basename $0)"
readonly VERSION='v0.1.0'

function main() {
  parse_flags $*
  moniter | execute
}
function parse_flags() {
  for opt in "$@"; do
    case $opt in
      -d|--directory)
        if [ $# -lt 2 ]; then
          echo "$NAME: option requires an argument -- '${1##*-}'"
          exit 2
        fi
        DIRECTORY="$2"
        shift 2
        ;;
      -d=*|--directory=*)
        DIRECTORY="$(eval echo ${1##*=})"
        shift 1
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      -v|--version)
        version
        exit 0
        ;;
      -*)
        echo "$NAME: unrecognized option -- '${1##*-}'"
        exit 2
        ;;
      *)
        break
        ;;
    esac
  done
  if [ $# -lt 1 ]; then
    echo "$NAME: no specify COMMAND"
    exit 2
  fi
  if [ -z "$(command -v ${1})" ]; then
    echo "$NAME: ${1}: cannot execute"
    exit 2
  fi
  CMD="${1}"
  ARGS=${@:2}
  DIRECTORY="${DIRECTORY:=`pwd`}"
}
function usage() {
  cat <<EOF
Usage: $NAME [OPTION]... COMMAND [ARGS]...
Execute COMMAND for changes to current directory.

Options:
  -d, --directory=PATH   Change monitored directory to PATH
  -h, --help             display this help text and exit
  -v, --version          display version information and exit
EOF
}
function version() {
  echo "$VERSION"
}
function moniter() {
  inotifywait \
    --event   'create,delete,modify,move' \
    --exclude '.*\.sw[pox]' \
    --quiet \
    --monitor \
    --recursive \
    "$DIRECTORY"
}
function execute() {
  set +e
  while read; do
    # ignore continuous notify
    while read -t 0.3; do
      :
    done
    clear
    ${CMD} ${ARGS}
  done
}

main $*
exit 0
