#!/usr/bin/env bash
set -eu
readonly PROG_NAME="$(basename $0)"
readonly VERSION='v0.1.0'

function main() {
  parse_flags $*
  moniter | execute
}
function parse_flags() {
  DIRECTORY=`pwd`
  if [ $# -lt 1 ]; then
    shortusage
    exit 2
  fi
  for opt in "$@"; do
    case $opt in
      -d|--directory)
        if [ $# -lt 2 ]; then
          echo "$PROG_NAME: option requires an argument -- '$1'"
          exit 2
        fi
        DIRECTORY="$2"
        shift 2
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      -v|--version)
        version
        exit 0
        ;;
      -*)
        echo "$PROG_NAME: unrecognized option -- '$1'"
        exit 2
        ;;
      *)
        if [ $# -eq 0 ]; then
          echo "$PROG_NAME: no specify COMMAND"
          exit 2
        fi
        CMD="${1}"
        ARGS=${@:2}
        break
        ;;
    esac
  done
}
function shortusage() {
  cat <<EOF
Usage: $PROG_NAME [OPTION]... COMMAND [ARGS]...
Try '$PROG_NAME --help' for more information.
EOF
}
function usage() {
  cat <<EOF
Usage: $PROG_NAME [OPTION]... COMMAND [ARGS]...
Execute COMMAND for changes to current directory.

Options:
  -d, --directory PATH   moniter under PATH
  -h, --help             display this help text and exit
  -v, --version          display version information and exit
EOF
}
function version() {
  echo "$VERSION"
}
function moniter() {
  inotifywait \
    --event   'create,delete,modify,move' \
    --exclude '.*\.sw[pox]' \
    --quiet \
    --monitor \
    --recursive \
    "$DIRECTORY"
}
function execute() {
  set +e
  while read; do
    # ignore continuous notify
    while read -t 0.3; do
      :
    done
    clear
    ${CMD} ${ARGS}
  done
}

main $*
exit 0
